### PR TITLE
Bugfix/incorrect input steps filament manager

### LINKED ISSUE #358: Spool Manager doesn't allow decimal prices
**Client or Server side error** 
Client

**Describe the bug**
Price field in Spool Manager won't allow decimal prices

**To Reproduce**
1. Go to Filament from top right menu
2. Click on Spool Manager
3. Enter price using a decimal (19.95 for example).
4. Field highlights red, error on hover reads "Please select a valid value. The two nearest values are 19 and 20"

**Expected behavior**
Price should be added as entered

**Screenshots**
(Sorry it's a camera shot...no way to screenshot the error on hover)

photo_2021-03-08_11-13-27

**Versions (please complete the following information):**
 - NodeJS Version: 12.20.1
 - OctoFarm Version: 1.1.11
 - OctoPrint Version: N/A
 - OctoPrint Plugins: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by NotExpectedYet**
Fixed #358

### CODE REVIEW

**Comment by NotExpectedYet** [comment]
Could do with merging this before fixing #353 as they're related. Found a few more bug's and oddities on it.

File: client_src/js/filamentManagement.js [hunk 1]
```diff
@@ -356,10 +356,10 @@ async function addSpool(
                   <td class="${displayNone}"><input class="form-control" type="text" placeholder="${
         post.spools.used
       }"></td>
-                  <td class="grams ${displayNone}">${(
+                              <td class="grams ${displayNone}">${(
```
Comment (davidzwa) [inline client_src/js/filamentManagement.js:359]: This whitespace makes no sense to me, however it's not a show stopper

**Review by davidzwa — APPROVED** [review]
LGTM - didnt test but I assume the step attribute works fine.

**Review by davidzwa — APPROVED** [review]
