### PR TITLE
Bugfix/double wrapped terminal commands

### LINKED ISSUE #240: Commands send from the Printer Control Terminal Double Wrapped Array
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Describe the bug**
When sending a command from Octofarm, it looks like the string is formattet in some strange way, resulting in Octoprint responding with an error

**To Reproduce**
1. Go to 'Printer'
2. Write G or M command in text field
3. Press send

**Expected behavior**
M or G codes being sent correctly, as entered in the text field.

**Screenshots**
image

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 13] 12.16.3-0017
 - OctoFarm Version [e.g. 1.5.5.7] 1.1.9-dev5
 - OctoPrint Version [e.g. 1.4.1] 1.5.3
 - OctoPrint Plugins [e.g. bed visualiser, octoklipper, printtimegenius] Enclosure Plugin

**Additional context**

### PR DESCRIPTION
**Pull request by NotExpectedYet**
Fixed #240

### CODE REVIEW

File: client_src/js/lib/modules/printerManager.js [hunk 1]
```diff
@@ -1707,22 +1707,22 @@ export default class PrinterManager {
...
       const flashReturn = function () {
-        elements.terminal.sendBtn = "btn btn-secondary";
+        elements.terminal.sendBtn.classList = "btn btn-secondary";
       };
       const opt = {
-        commands: [input],
+        commands: input,
       };
-
+      console.log(opt)
```
Comment (davidzwa) [inline client_src/js/lib/modules/printerManager.js:1715]: Log, should remove or apply logger with filter :)

**Review by davidzwa — COMMENTED** [review]
1 console log that should be removed

**Comment by NotExpectedYet** [comment]
I'll sort that cheers missed it

**Review by davidzwa — APPROVED** [review]
